apiVersion: apps/v1
kind: Deployment
metadata:
  name: intdb-deployment
spec:
  selector:
    matchLabels:
      app: intdb-app
  replicas: 1
  template:
    metadata:
      labels:
        app: intdb-app
    spec:
      containers:
      - name: intdb
        image: lidorabo/docker_repo:int_db
        ports:
        - containerPort: 201
        readinessProbe:
          httpGet:
            path: /
            port: 27017
